//
// ForecastDataAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

private let apikey = "358389cc2e7b7f987ac85f1075b911c6"
open class ForecastDataAPI {

    /**
     Get weather forecast data for one location
     
     - parameter q: (query) City name and optionally the country code divided by comma; use ISO 3166 country codes. (optional)
     - parameter cnt: (query) Number of days to forecast (max 16 days) (optional, default to 7)
     - parameter appid: (query) API key to authorize requests (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func dailyForecast(q: String? = nil, cnt: Int? = nil, appid: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Forecast?, _ error: Error?) -> Void)) -> RequestTask {
        return dailyForecastWithRequestBuilder(q: q, cnt: cnt, appid: appid).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get weather forecast data for one location
     - GET /forecast/
     - Retrieve the weather forecast
     - API Key:
       - type: apiKey appid (QUERY)
       - name: app_id
     - parameter q: (query) City name and optionally the country code divided by comma; use ISO 3166 country codes. (optional)
     - parameter cnt: (query) Number of days to forecast (max 16 days) (optional, default to 7)
     - parameter appid: (query) API key to authorize requests (optional)
     - returns: RequestBuilder<Forecast> 
     */
    open class func dailyForecastWithRequestBuilder(q: String? = nil, cnt: Int? = nil, appid: String? = nil) -> RequestBuilder<Forecast> {
        let localVariablePath = "/forecast/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        var localVariableParameters: [String: Any] = [:]
        localVariableParameters["appid"] = apikey

        if let city = q {
            localVariableParameters["q"] = city
        }

        if let count = cnt {
            localVariableParameters["cnt"] = count
        }

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
            "cnt": (wrappedValue: cnt?.encodeToJSON(), isExplode: true),
            "appid": (wrappedValue: appid?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Forecast>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}

