//
// City.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct City: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var name: String?
    public var coord: Coord?
    public var country: String?

    public init(id: Int? = nil, name: String? = nil, coord: Coord? = nil, country: String? = nil) {
        self.id = id
        self.name = name
        self.coord = coord
        self.country = country
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case coord
        case country
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(coord, forKey: .coord)
        try container.encodeIfPresent(country, forKey: .country)
    }
}

