//
// ForecastItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ForecastItem: Codable, JSONEncodable, Hashable {

    public var dt: Int?
    public var main: Main?
    public var weather: [Weather]?
    public var clouds: Clouds?
    public var wind: Wind?
    public var rain: Rain?
    public var snow: Snow?
    public var sys: Sys?
    public var dtTxt: String?

    public init(dt: Int? = nil, main: Main? = nil, weather: [Weather]? = nil, clouds: Clouds? = nil, wind: Wind? = nil, rain: Rain? = nil, snow: Snow? = nil, sys: Sys? = nil, dtTxt: String? = nil) {
        self.dt = dt
        self.main = main
        self.weather = weather
        self.clouds = clouds
        self.wind = wind
        self.rain = rain
        self.snow = snow
        self.sys = sys
        self.dtTxt = dtTxt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dt
        case main
        case weather
        case clouds
        case wind
        case rain
        case snow
        case sys
        case dtTxt = "dt_txt"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dt, forKey: .dt)
        try container.encodeIfPresent(main, forKey: .main)
        try container.encodeIfPresent(weather, forKey: .weather)
        try container.encodeIfPresent(clouds, forKey: .clouds)
        try container.encodeIfPresent(wind, forKey: .wind)
        try container.encodeIfPresent(rain, forKey: .rain)
        try container.encodeIfPresent(snow, forKey: .snow)
        try container.encodeIfPresent(sys, forKey: .sys)
        try container.encodeIfPresent(dtTxt, forKey: .dtTxt)
    }
}

