//
// Forecast.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Forecast: Codable, JSONEncodable, Hashable {

    public var city: City?
    public var list: [ForecastItem]?

    public init(city: City? = nil, list: [ForecastItem]? = nil) {
        self.city = city
        self.list = list
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case city
        case list
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(list, forKey: .list)
    }
}

